/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppSenhasLinksRouteImport } from './routes/_app/senhas-links'
import { Route as AppRhRouteImport } from './routes/_app/rh'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppPedagogicoRouteImport } from './routes/_app/pedagogico'
import { Route as AppMarketingRouteImport } from './routes/_app/marketing'
import { Route as AppIaRouteImport } from './routes/_app/ia'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppEmpresarioRouteImport } from './routes/_app/empresario'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContratosRouteImport } from './routes/_app/contratos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppComercialRouteImport } from './routes/_app/comercial'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppAlunosRouteImport } from './routes/_app/alunos'
import { Route as AppRhIndexRouteImport } from './routes/_app/rh.index'
import { Route as AppRhSetorRouteImport } from './routes/_app/rh.$setor'
import { Route as AppRhSetorIndexRouteImport } from './routes/_app/rh.$setor.index'
import { Route as AppRhSetorColaboradorIdRouteImport } from './routes/_app/rh.$setor.$colaboradorId'
import { Route as AppRhSetorColaboradorIdIndexRouteImport } from './routes/_app/rh.$setor.$colaboradorId.index'
import { Route as AppRhSetorColaboradorIdDocumentoTipoRouteImport } from './routes/_app/rh.$setor.$colaboradorId.documento.$tipo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSenhasLinksRoute = AppSenhasLinksRouteImport.update({
  id: '/senhas-links',
  path: '/senhas-links',
  getParentRoute: () => AppRoute,
} as any)
const AppRhRoute = AppRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPedagogicoRoute = AppPedagogicoRouteImport.update({
  id: '/pedagogico',
  path: '/pedagogico',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresarioRoute = AppEmpresarioRouteImport.update({
  id: '/empresario',
  path: '/empresario',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunosRoute = AppAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AppRoute,
} as any)
const AppRhIndexRoute = AppRhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRhRoute,
} as any)
const AppRhSetorRoute = AppRhSetorRouteImport.update({
  id: '/$setor',
  path: '/$setor',
  getParentRoute: () => AppRhRoute,
} as any)
const AppRhSetorIndexRoute = AppRhSetorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRhSetorRoute,
} as any)
const AppRhSetorColaboradorIdRoute = AppRhSetorColaboradorIdRouteImport.update({
  id: '/$colaboradorId',
  path: '/$colaboradorId',
  getParentRoute: () => AppRhSetorRoute,
} as any)
const AppRhSetorColaboradorIdIndexRoute =
  AppRhSetorColaboradorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppRhSetorColaboradorIdRoute,
  } as any)
const AppRhSetorColaboradorIdDocumentoTipoRoute =
  AppRhSetorColaboradorIdDocumentoTipoRouteImport.update({
    id: '/documento/$tipo',
    path: '/documento/$tipo',
    getParentRoute: () => AppRhSetorColaboradorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alunos': typeof AppAlunosRoute
  '/calendario': typeof AppCalendarioRoute
  '/comercial': typeof AppComercialRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresario': typeof AppEmpresarioRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/ia': typeof AppIaRoute
  '/marketing': typeof AppMarketingRoute
  '/pedagogico': typeof AppPedagogicoRoute
  '/perfil': typeof AppPerfilRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/rh': typeof AppRhRouteWithChildren
  '/senhas-links': typeof AppSenhasLinksRoute
  '/usuarios': typeof AppUsuariosRoute
  '/rh/$setor': typeof AppRhSetorRouteWithChildren
  '/rh/': typeof AppRhIndexRoute
  '/rh/$setor/$colaboradorId': typeof AppRhSetorColaboradorIdRouteWithChildren
  '/rh/$setor/': typeof AppRhSetorIndexRoute
  '/rh/$setor/$colaboradorId/': typeof AppRhSetorColaboradorIdIndexRoute
  '/rh/$setor/$colaboradorId/documento/$tipo': typeof AppRhSetorColaboradorIdDocumentoTipoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alunos': typeof AppAlunosRoute
  '/calendario': typeof AppCalendarioRoute
  '/comercial': typeof AppComercialRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresario': typeof AppEmpresarioRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/ia': typeof AppIaRoute
  '/marketing': typeof AppMarketingRoute
  '/pedagogico': typeof AppPedagogicoRoute
  '/perfil': typeof AppPerfilRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/senhas-links': typeof AppSenhasLinksRoute
  '/usuarios': typeof AppUsuariosRoute
  '/rh': typeof AppRhIndexRoute
  '/rh/$setor': typeof AppRhSetorIndexRoute
  '/rh/$setor/$colaboradorId': typeof AppRhSetorColaboradorIdIndexRoute
  '/rh/$setor/$colaboradorId/documento/$tipo': typeof AppRhSetorColaboradorIdDocumentoTipoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alunos': typeof AppAlunosRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/comercial': typeof AppComercialRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresario': typeof AppEmpresarioRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/ia': typeof AppIaRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/pedagogico': typeof AppPedagogicoRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/rh': typeof AppRhRouteWithChildren
  '/_app/senhas-links': typeof AppSenhasLinksRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/rh/$setor': typeof AppRhSetorRouteWithChildren
  '/_app/rh/': typeof AppRhIndexRoute
  '/_app/rh/$setor/$colaboradorId': typeof AppRhSetorColaboradorIdRouteWithChildren
  '/_app/rh/$setor/': typeof AppRhSetorIndexRoute
  '/_app/rh/$setor/$colaboradorId/': typeof AppRhSetorColaboradorIdIndexRoute
  '/_app/rh/$setor/$colaboradorId/documento/$tipo': typeof AppRhSetorColaboradorIdDocumentoTipoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alunos'
    | '/calendario'
    | '/comercial'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresario'
    | '/financeiro'
    | '/ia'
    | '/marketing'
    | '/pedagogico'
    | '/perfil'
    | '/relatorios'
    | '/rh'
    | '/senhas-links'
    | '/usuarios'
    | '/rh/$setor'
    | '/rh/'
    | '/rh/$setor/$colaboradorId'
    | '/rh/$setor/'
    | '/rh/$setor/$colaboradorId/'
    | '/rh/$setor/$colaboradorId/documento/$tipo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alunos'
    | '/calendario'
    | '/comercial'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresario'
    | '/financeiro'
    | '/ia'
    | '/marketing'
    | '/pedagogico'
    | '/perfil'
    | '/relatorios'
    | '/senhas-links'
    | '/usuarios'
    | '/rh'
    | '/rh/$setor'
    | '/rh/$setor/$colaboradorId'
    | '/rh/$setor/$colaboradorId/documento/$tipo'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alunos'
    | '/_app/calendario'
    | '/_app/comercial'
    | '/_app/configuracoes'
    | '/_app/contratos'
    | '/_app/dashboard'
    | '/_app/empresario'
    | '/_app/financeiro'
    | '/_app/ia'
    | '/_app/marketing'
    | '/_app/pedagogico'
    | '/_app/perfil'
    | '/_app/relatorios'
    | '/_app/rh'
    | '/_app/senhas-links'
    | '/_app/usuarios'
    | '/_app/rh/$setor'
    | '/_app/rh/'
    | '/_app/rh/$setor/$colaboradorId'
    | '/_app/rh/$setor/'
    | '/_app/rh/$setor/$colaboradorId/'
    | '/_app/rh/$setor/$colaboradorId/documento/$tipo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/senhas-links': {
      id: '/_app/senhas-links'
      path: '/senhas-links'
      fullPath: '/senhas-links'
      preLoaderRoute: typeof AppSenhasLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rh': {
      id: '/_app/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AppRhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedagogico': {
      id: '/_app/pedagogico'
      path: '/pedagogico'
      fullPath: '/pedagogico'
      preLoaderRoute: typeof AppPedagogicoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia': {
      id: '/_app/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresario': {
      id: '/_app/empresario'
      path: '/empresario'
      fullPath: '/empresario'
      preLoaderRoute: typeof AppEmpresarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comercial': {
      id: '/_app/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alunos': {
      id: '/_app/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AppAlunosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rh/': {
      id: '/_app/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof AppRhIndexRouteImport
      parentRoute: typeof AppRhRoute
    }
    '/_app/rh/$setor': {
      id: '/_app/rh/$setor'
      path: '/$setor'
      fullPath: '/rh/$setor'
      preLoaderRoute: typeof AppRhSetorRouteImport
      parentRoute: typeof AppRhRoute
    }
    '/_app/rh/$setor/': {
      id: '/_app/rh/$setor/'
      path: '/'
      fullPath: '/rh/$setor/'
      preLoaderRoute: typeof AppRhSetorIndexRouteImport
      parentRoute: typeof AppRhSetorRoute
    }
    '/_app/rh/$setor/$colaboradorId': {
      id: '/_app/rh/$setor/$colaboradorId'
      path: '/$colaboradorId'
      fullPath: '/rh/$setor/$colaboradorId'
      preLoaderRoute: typeof AppRhSetorColaboradorIdRouteImport
      parentRoute: typeof AppRhSetorRoute
    }
    '/_app/rh/$setor/$colaboradorId/': {
      id: '/_app/rh/$setor/$colaboradorId/'
      path: '/'
      fullPath: '/rh/$setor/$colaboradorId/'
      preLoaderRoute: typeof AppRhSetorColaboradorIdIndexRouteImport
      parentRoute: typeof AppRhSetorColaboradorIdRoute
    }
    '/_app/rh/$setor/$colaboradorId/documento/$tipo': {
      id: '/_app/rh/$setor/$colaboradorId/documento/$tipo'
      path: '/documento/$tipo'
      fullPath: '/rh/$setor/$colaboradorId/documento/$tipo'
      preLoaderRoute: typeof AppRhSetorColaboradorIdDocumentoTipoRouteImport
      parentRoute: typeof AppRhSetorColaboradorIdRoute
    }
  }
}

interface AppRhSetorColaboradorIdRouteChildren {
  AppRhSetorColaboradorIdIndexRoute: typeof AppRhSetorColaboradorIdIndexRoute
  AppRhSetorColaboradorIdDocumentoTipoRoute: typeof AppRhSetorColaboradorIdDocumentoTipoRoute
}

const AppRhSetorColaboradorIdRouteChildren: AppRhSetorColaboradorIdRouteChildren =
  {
    AppRhSetorColaboradorIdIndexRoute: AppRhSetorColaboradorIdIndexRoute,
    AppRhSetorColaboradorIdDocumentoTipoRoute:
      AppRhSetorColaboradorIdDocumentoTipoRoute,
  }

const AppRhSetorColaboradorIdRouteWithChildren =
  AppRhSetorColaboradorIdRoute._addFileChildren(
    AppRhSetorColaboradorIdRouteChildren,
  )

interface AppRhSetorRouteChildren {
  AppRhSetorColaboradorIdRoute: typeof AppRhSetorColaboradorIdRouteWithChildren
  AppRhSetorIndexRoute: typeof AppRhSetorIndexRoute
}

const AppRhSetorRouteChildren: AppRhSetorRouteChildren = {
  AppRhSetorColaboradorIdRoute: AppRhSetorColaboradorIdRouteWithChildren,
  AppRhSetorIndexRoute: AppRhSetorIndexRoute,
}

const AppRhSetorRouteWithChildren = AppRhSetorRoute._addFileChildren(
  AppRhSetorRouteChildren,
)

interface AppRhRouteChildren {
  AppRhSetorRoute: typeof AppRhSetorRouteWithChildren
  AppRhIndexRoute: typeof AppRhIndexRoute
}

const AppRhRouteChildren: AppRhRouteChildren = {
  AppRhSetorRoute: AppRhSetorRouteWithChildren,
  AppRhIndexRoute: AppRhIndexRoute,
}

const AppRhRouteWithChildren = AppRhRoute._addFileChildren(AppRhRouteChildren)

interface AppRouteChildren {
  AppAlunosRoute: typeof AppAlunosRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppComercialRoute: typeof AppComercialRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresarioRoute: typeof AppEmpresarioRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppIaRoute: typeof AppIaRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppPedagogicoRoute: typeof AppPedagogicoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRhRoute: typeof AppRhRouteWithChildren
  AppSenhasLinksRoute: typeof AppSenhasLinksRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlunosRoute: AppAlunosRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppComercialRoute: AppComercialRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresarioRoute: AppEmpresarioRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppIaRoute: AppIaRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppPedagogicoRoute: AppPedagogicoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRhRoute: AppRhRouteWithChildren,
  AppSenhasLinksRoute: AppSenhasLinksRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
