/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppEmpresarioRouteImport } from './routes/_app/empresario'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContratosRouteImport } from './routes/_app/contratos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppAlunosRouteImport } from './routes/_app/alunos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresarioRoute = AppEmpresarioRouteImport.update({
  id: '/empresario',
  path: '/empresario',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunosRoute = AppAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alunos': typeof AppAlunosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresario': typeof AppEmpresarioRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/perfil': typeof AppPerfilRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alunos': typeof AppAlunosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresario': typeof AppEmpresarioRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/perfil': typeof AppPerfilRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alunos': typeof AppAlunosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresario': typeof AppEmpresarioRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alunos'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresario'
    | '/financeiro'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alunos'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresario'
    | '/financeiro'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alunos'
    | '/_app/configuracoes'
    | '/_app/contratos'
    | '/_app/dashboard'
    | '/_app/empresario'
    | '/_app/financeiro'
    | '/_app/perfil'
    | '/_app/relatorios'
    | '/_app/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresario': {
      id: '/_app/empresario'
      path: '/empresario'
      fullPath: '/empresario'
      preLoaderRoute: typeof AppEmpresarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alunos': {
      id: '/_app/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AppAlunosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlunosRoute: typeof AppAlunosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresarioRoute: typeof AppEmpresarioRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlunosRoute: AppAlunosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresarioRoute: AppEmpresarioRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
